version: '3.4'

services:
  web:
    image: aspnet-mvc-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "44390:443"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
