FROM mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2019

SHELL ["powershell", "-Command"]

# Tạo thư mục app
RUN New-Item -Path 'C:\webapp' -ItemType Directory

# Copy các file publish vào container
COPY WebShoeShop/WebShoeShop/bin/App.publish/PublishOutput/ /inetpub/wwwroot/
