name: Khai Do  # Tên của workflow này là "Khai Do"

on:  # Sự kiện kích hoạt workflow
  push:  # Khi có code được đẩy lên
    branches: [ main, master ]  # Chỉ áp dụng cho nhánh main và master
  pull_request:  # Khi có pull request được tạo hoặc cập nhật
    branches: [ main, master ]  # Áp dụng cho nhánh main và master

jobs:
  chau_tu:  # Tên của job là "chau_tu"
    timeout-minutes: 60  # Giới hạn thời gian chạy là 60 phút
    runs-on: ubuntu-latest  # Chạy trên máy ảo Ubuntu mới nhất

    steps:  # Các bước thực hiện trong job
      - uses: actions/checkout@v4  # Bước đầu tiên: checkout source code từ repo
      - uses: actions/setup-node@v4  # Thiết lập môi trường Node.js
        with:
          node-version: lts/*  # Dùng phiên bản Node LTS mới nhất

      - name: Install dependencies  # Cài đặt các thư viện phụ thuộc
        run: npm ci  # Cài đặt thông qua npm (clean install)

      - name: Install Playwright Browsers  # Cài các trình duyệt cần thiết cho Playwright
        run: npx playwright install --with-deps  # Cài playwright kèm theo các dependencies

      - name: Run Playwright tests  # Chạy các bài test bằng Playwright
        run: npx playwright test  # Lệnh chạy test

      - uses: actions/upload-artifact@v4  # Tải artifact (kết quả) lên nếu bị hủy
        if: ${{ !cancelled() }}  # Chỉ thực hiện nếu workflow không bị hủy
        with:
          name: playwright-report  # Tên artifact là "playwright-report"
          path: playwright-report/  # Đường dẫn thư mục chứa báo cáo
          retention-days: 30  # Lưu trữ artifact trong 30 ngày
