name: Playwright Tests for ASP.NET MVC (.NET Framework)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Build ASP.NET MVC project (.NET Framework)
      shell: powershell
      run: |
        $msbuildPath = "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe"
        if (-Not (Test-Path $msbuildPath)) {
          throw "MSBuild.exe not found at expected location: $msbuildPath"
        }
        & "$msbuildPath" "WebShoeShop/WebShoeShop.csproj" /p:Configuration=Release /p:Platform="Any CPU"

    - name: Start ASP.NET MVC app using IIS Express
      shell: powershell
      run: |
        $iisExpressPath = "${env:ProgramFiles(x86)}\IIS Express\iisexpress.exe"
        if (-not (Test-Path $iisExpressPath)) {
          Write-Error "IIS Express không được cài đặt trên runner."
          exit 1
        }

        Start-Process -FilePath $iisExpressPath `
                      -ArgumentList "/path:$PWD\WebShoeShop", "/port:44390" `
                      -NoNewWindow
        Write-Host "Waiting for server to start..."
        Start-Sleep -Seconds 15

    - name: Run Playwright tests
      run: npx playwright test
      env:
        BASE_URL: http://localhost:44390

    - name: Upload test report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
