name: Playwright Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Start .NET server in background
      shell: powershell
      run: |
        Start-Process "dotnet" "run --project ./WebShoeShop/WebShoeShop --urls=http://localhost:44390"
        $maxAttempts = 180
        $i = 0
        do {
          try {
            $response = Invoke-WebRequest http://localhost:44390 -UseBasicParsing -TimeoutSec 2
            if ($response.StatusCode -eq 200) {
              Write-Output "Server is up!"
              break
            }
          } catch {
            Write-Output "Waiting for server..."
            Start-Sleep -Seconds 1
          }
          $i++
        } while ($i -lt $maxAttempts)

    - name: Run Playwright tests
      run: npx playwright test
      env:
        BASE_URL: http://localhost:44390

    - name: Upload test report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
