name: Khai Do

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  chau_tu:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup .NET SDK nếu là dự án .NET
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.203' # Hoặc phiên bản bạn dùng

      - name: Restore .NET dependencies
        run: dotnet restore WebShoeShop/WebShoeShop.csproj

      - name: Build .NET app
        run: dotnet build WebShoeShop/WebShoeShop.csproj --configuration Release

      - name: Run web server
        run: dotnet run --project WebShoeShop/WebShoeShop.csproj --urls https://localhost:44390/ &
        env:
          ASPNETCORE_ENVIRONMENT: Development

      - name: Wait for app to be ready
        run: npx wait-on https://localhost:44390/

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: HOMEPAGEURL= https://localhost:44390/ npx playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
